### ISSUE TITLE
Don't hardcode the architecture

### ISSUE THREAD

**Issue by multun** [alexkirsz/dvirt#2]
https://github.com/alexkirsz/dvirt/blob/master/Dockerfile#L22

C sho gros

**Comment by alexkirsz** [comment]
How would you have me do it? Since I'm hardcoding the source image it's not like this is going to change anytime soon. In fact, I believe this is exactly what https://github.com/emk/rust-musl-builder recommends.

**Comment by multun** [comment]
You could change

`RUN cargo build --release`

to 

`RUN cargo build --release && mv /app/target/*/release/dvirt /`

This way you don't have to hardcode the architecture anywhere.

**Comment by alexkirsz** [comment]
Wouldn't work, there's more than one folder in /app/target. I'll define an argument for the target architecture.

**Comment by alexkirsz** [comment]
Fixed in 2fb50a3f2a81eafdfe7ceb6aa01f8870fc6c7bba
