### ISSUE TITLE
Use a packer

### ISSUE THREAD

**Issue by multun** [alexkirsz/dvirt#3]
https://upx.github.io/

**Comment by alexkirsz** [comment]
P A C C

**Comment by alexkirsz** [comment]
![image](https://user-images.githubusercontent.com/1621758/66272017-b73b4800-e864-11e9-8842-643efa85424a.png)

P A C C D

**Comment by alexkirsz** [comment]
Fixed in 2fb50a3f2a81eafdfe7ceb6aa01f8870fc6c7bba
